# Generated by Django 5.2.9 on 2025-12-30 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IRIS_BADGES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('target_audience', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('BOTH', 'Both')], default='INTERNAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'IRIS_CHALLENGES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'IRIS_USERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('idea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented'), ('ARCHIVED', 'Archived')], default='SUBMITTED', max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
                ('sharing_scope', models.CharField(choices=[('CUSTOMER', 'Customer'), ('ECOSYSTEM', 'Ecosystem'), ('PUBLIC', 'Public'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'IRIS_IDEAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdeaCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('theme_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'IRIS_IDEA_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IRIS_ROLES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChallengePanel',
            fields=[
                ('panel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('round_number', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.challenge')),
            ],
            options={
                'db_table': 'IRIS_CHALLENGE_PANELS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.irisuser'),
        ),
        migrations.CreateModel(
            name='IdeaDetail',
            fields=[
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='iris_app.idea')),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('proposed_solution', models.TextField(blank=True, null=True)),
                ('business_value_monetary', models.TextField(blank=True, null=True)),
                ('business_value_non_monetary', models.TextField(blank=True, null=True)),
                ('assumptions', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('innovation_type', models.CharField(blank=True, choices=[('INCREMENTAL', 'Incremental'), ('ADJACENT', 'Adjacent'), ('DISRUPTIVE', 'Disruptive')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'IRIS_IDEA_DETAILS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.challenge'),
        ),
        migrations.AddField(
            model_name='idea',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.irisuser'),
        ),
        migrations.CreateModel(
            name='IdeaDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.idea')),
            ],
            options={
                'db_table': 'IRIS_IDEA_DOCUMENTS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('CHALLENGE_SOLUTION', 'Challenge Solution')], max_length=20, null=True)),
                ('entity_id', models.UUIDField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REWORK', 'Rework')], max_length=20, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_REVIEWS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_REWARDS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, max_length=20, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_WORKFLOW_LOGS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='iris_app.irisuser')),
                ('current_project_code', models.CharField(blank=True, max_length=50, null=True)),
                ('current_project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('pm_dm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_line', models.CharField(blank=True, max_length=100, null=True)),
                ('ibu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporters', to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_EMPLOYEE_DETAILS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChallengeMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.challengepanel')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_CHALLENGE_MENTORS',
                'managed': True,
                'unique_together': {('panel', 'mentor')},
            },
        ),
        migrations.CreateModel(
            name='CoIdeator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.idea')),
            ],
            options={
                'db_table': 'IRIS_CO_IDEATORS',
                'managed': True,
                'unique_together': {('idea', 'user')},
            },
        ),
        migrations.CreateModel(
            name='IdeaCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.ideacategory')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.idea')),
            ],
            options={
                'db_table': 'IRIS_IDEA_CATEGORY_MAPPING',
                'managed': True,
                'unique_together': {('idea', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_USER_BADGES',
                'managed': True,
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_USER_ROLES',
                'managed': True,
                'unique_together': {('user', 'role')},
            },
        ),
    ]
