# Generated by Django 5.2.9 on 2026-02-19 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IRIS_BADGES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('challenge_icon', models.ImageField(blank=True, null=True, upload_to='challenge_icons/')),
                ('round1_eval_start', models.DateTimeField(blank=True, null=True)),
                ('round1_eval_end', models.DateTimeField(blank=True, null=True)),
                ('round2_eval_start', models.DateTimeField(blank=True, null=True)),
                ('round2_eval_end', models.DateTimeField(blank=True, null=True)),
                ('key_insights', models.TextField(blank=True, null=True)),
                ('expected_outcome', models.TextField(blank=True, null=True)),
                ('round1_eval_criteria', models.TextField(blank=True, null=True)),
                ('has_idea_template', models.BooleanField(default=False)),
                ('idea_template_file', models.FileField(blank=True, null=True, upload_to='challenge_templates/')),
                ('challenge_document', models.FileField(blank=True, null=True, upload_to='challenge_docs/')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('ibu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('target_audience', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('BOTH', 'Both')], default='INTERNAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('num_rounds', models.IntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'IRIS_CHALLENGES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'IRIS_USERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('idea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented'), ('ARCHIVED', 'Archived')], default='SUBMITTED', max_length=50)),
                ('is_confidential', models.BooleanField(default=False)),
                ('sharing_scope', models.CharField(choices=[('CUSTOMER', 'Customer'), ('ECOSYSTEM', 'Ecosystem'), ('PUBLIC', 'Public'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'IRIS_IDEAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdeaCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('theme_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'IRIS_IDEA_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImprovementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'IRIS_IMPROVEMENT_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisClusterIbgIbu',
            fields=[
                ('functioncode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('function_type', models.CharField(max_length=10)),
                ('function_lg_desc', models.CharField(max_length=100)),
                ('function_head', models.CharField(blank=True, max_length=11, null=True)),
                ('function_gdu', models.CharField(blank=True, max_length=50, null=True)),
                ('function_gdu_head', models.CharField(blank=True, max_length=11, null=True)),
                ('function_sdu', models.CharField(blank=True, max_length=50, null=True)),
                ('function_sdu_head', models.CharField(blank=True, max_length=11, null=True)),
                ('function_status', models.CharField(max_length=1)),
                ('function_level', models.CharField(max_length=15)),
                ('function_evp', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'IRIS_CLUSTER_IBG_IBU',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisCollage',
            fields=[
                ('collage_id', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('university_id', models.DecimalField(decimal_places=0, max_digits=38)),
                ('collage_name', models.CharField(max_length=200)),
                ('collage_description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Collage',
                'verbose_name_plural': 'Collages',
                'db_table': 'IRIS_COLLAGE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisEmployeeMaster',
            fields=[
                ('empcode', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('empname', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.DateTimeField(blank=True, null=True)),
                ('emailid', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_exp', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ('tm_exp', models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ('officercode', models.CharField(blank=True, max_length=1, null=True)),
                ('emptitle', models.CharField(blank=True, max_length=50, null=True)),
                ('project_id', models.CharField(blank=True, max_length=20, null=True)),
                ('status_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('jobcode', models.CharField(blank=True, max_length=10, null=True)),
                ('functioncode', models.CharField(blank=True, max_length=30, null=True)),
                ('base_location', models.CharField(blank=True, max_length=40, null=True)),
                ('current_location', models.CharField(blank=True, max_length=40, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=11, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('empl_status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'IRIS_EMPLOYEE_MASTER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisGradeRoleMaster',
            fields=[
                ('role_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_band', models.CharField(blank=True, max_length=200, null=True)),
                ('role_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'IRIS_GRADE_ROLE_MASTER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisLocationMaster',
            fields=[
                ('location_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'IRIS_LOCATION_MASTER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisMailMaster',
            fields=[
                ('status_id', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('mail_subject', models.CharField(max_length=200)),
                ('mail_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IRIS_MAIL_MASTER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrisRoleMs',
            fields=[
                ('rolecode', models.DecimalField(decimal_places=0, max_digits=38, primary_key=True, serialize=False)),
                ('role_sh_desc', models.CharField(max_length=50)),
                ('role_lg_desc', models.CharField(max_length=100)),
                ('grade_desc', models.CharField(blank=True, max_length=5, null=True)),
                ('job_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_flag', models.CharField(max_length=1)),
                ('job_family', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Role Master',
                'verbose_name_plural': 'Role Masters',
                'db_table': 'IRIS_ROLE_MS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReviewParameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'IRIS_REVIEW_PARAMETERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IRIS_ROLES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChallengePanel',
            fields=[
                ('panel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('round_number', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.challenge')),
            ],
            options={
                'db_table': 'IRIS_CHALLENGE_PANELS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_challenges', to='iris_app.irisuser'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to='iris_app.irisuser'),
        ),
        migrations.CreateModel(
            name='GrassrootIdea',
            fields=[
                ('idea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_value', models.TextField()),
                ('monetary_value', models.TextField()),
                ('proposed_idea', models.TextField()),
                ('non_monetary_value', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('assumptions', models.TextField()),
                ('key_risks', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED_RM', 'Submitted to RM'), ('REWORK_RM', 'Rework Required by RM'), ('APPROVED_RM', 'Approved by RM'), ('REJECTED_RM', 'Rejected by RM'), ('SUBMITTED_IBU', 'Submitted to IBU'), ('REWORK_IBU', 'Rework Required by IBU'), ('APPROVED_IBU', 'Approved by IBU'), ('REJECTED_IBU', 'Rejected by IBU'), ('PENDING_CUSTOMER', 'Pending Customer Input'), ('COMPLETED', 'Completed')], default='SUBMITTED_RM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidentiality', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('innovation_context', models.CharField(blank=True, max_length=100, null=True)),
                ('ideator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grassroot_ideas', to='iris_app.irisuser')),
                ('improvement_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.improvementcategory')),
            ],
            options={
                'db_table': 'IRIS_GRASSROOT_IDEAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrassrootEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_role', models.CharField(max_length=20)),
                ('is_desirable', models.BooleanField(default=False)),
                ('is_feasible', models.BooleanField(default=False)),
                ('is_viable', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='iris_app.grassrootidea')),
            ],
            options={
                'db_table': 'IRIS_GRASSROOT_EVALUATIONS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdeaDetail',
            fields=[
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='iris_app.idea')),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('proposed_solution', models.TextField(blank=True, null=True)),
                ('business_value_monetary', models.TextField(blank=True, null=True)),
                ('business_value_non_monetary', models.TextField(blank=True, null=True)),
                ('assumptions', models.TextField(blank=True, null=True)),
                ('risks', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('innovation_type', models.CharField(blank=True, choices=[('INCREMENTAL', 'Incremental'), ('ADJACENT', 'Adjacent'), ('DISRUPTIVE', 'Disruptive')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'IRIS_IDEA_DETAILS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.challenge'),
        ),
        migrations.AddField(
            model_name='idea',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.irisuser'),
        ),
        migrations.CreateModel(
            name='IdeaDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.FileField(upload_to='idea_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.idea')),
            ],
            options={
                'db_table': 'IRIS_IDEA_DOCUMENTS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImprovementSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='iris_app.improvementcategory')),
            ],
            options={
                'db_table': 'IRIS_IMPROVEMENT_SUB_CATEGDE2E',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='grassrootidea',
            name='improvement_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.improvementsubcategory'),
        ),
        migrations.AddField(
            model_name='irisuser',
            name='employee_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_users', to='iris_app.irisemployeemaster'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='iris_app.irisuser')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_NOTIFICATIONS',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('CHALLENGE_SOLUTION', 'Challenge Solution')], max_length=20, null=True)),
                ('entity_id', models.UUIDField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REWORK', 'Rework')], max_length=20, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_REVIEWS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_REWARDS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_USER_LOGIN_LOGS',
                'ordering': ['-login_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_USER_ROLES',
                'managed': True,
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeOwner',
            fields=[
            ],
            options={
                'verbose_name': 'Challenge Owner',
                'verbose_name_plural': 'Challenge Owners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('iris_app.userrole',),
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, max_length=20, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_WORKFLOW_LOGS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='iris_app.irisuser')),
                ('current_project_code', models.CharField(blank=True, max_length=50, null=True)),
                ('current_project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('pm_dm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_line', models.CharField(blank=True, max_length=100, null=True)),
                ('ibu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporters', to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_EMPLOYEE_DETAILS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChallengeMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.challengepanel')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_CHALLENGE_MENTORS',
                'managed': True,
                'unique_together': {('panel', 'mentor')},
            },
        ),
        migrations.CreateModel(
            name='CoIdeator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.idea')),
            ],
            options={
                'db_table': 'IRIS_CO_IDEATORS',
                'managed': True,
                'unique_together': {('idea', 'user')},
            },
        ),
        migrations.CreateModel(
            name='IdeaCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.ideacategory')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.idea')),
            ],
            options={
                'db_table': 'IRIS_IDEA_CATEGORY_MAPPING',
                'managed': True,
                'unique_together': {('idea', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeReviewParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.IntegerField(help_text='Weightage (e.g., 5, 10, 15, 20). Total must be 100.')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_parameters', to='iris_app.challenge')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.reviewparameter')),
            ],
            options={
                'db_table': 'IRIS_CHALLENGE_REVIEW_PARAMS',
                'managed': True,
                'unique_together': {('challenge', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.reviewparameter')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='iris_app.review')),
            ],
            options={
                'db_table': 'IRIS_REVIEW_RATINGS',
                'managed': True,
                'unique_together': {('review', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_USER_BADGES',
                'managed': True,
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
