# Generated by Django 5.2.9 on 2025-12-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewParameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'IRIS_REVIEW_PARAMETERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChallengeOwner',
            fields=[
            ],
            options={
                'verbose_name': 'Challenge Owner',
                'verbose_name_plural': 'Challenge Owners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('iris_app.userrole',),
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.reviewparameter')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='iris_app.review')),
            ],
            options={
                'db_table': 'IRIS_REVIEW_RATINGS',
                'managed': True,
                'unique_together': {('review', 'parameter')},
            },
        ),
    ]
