# Generated by Django 5.2.9 on 2026-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideadetail',
            old_name='business_value_non_monetary',
            new_name='business_monetary',
        ),
        migrations.AddField(
            model_name='challengepanel',
            name='emailid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='challengepanel',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challengepanel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengepanel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='emailid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='empcode',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='empname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='ibu_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='improvement_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='improvement_theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='service_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ideadetail',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideadetail',
            name='technology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
