# Generated by Django 5.2.9 on 2025-12-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0002_reviewparameter_challengeowner_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_document',
            field=models.FileField(blank=True, null=True, upload_to='challenge_docs/'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='expected_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='has_idea_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='idea_template_file',
            field=models.FileField(blank=True, null=True, upload_to='challenge_templates/'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='key_insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='round1_eval_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='round2_eval_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChallengeReviewParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.IntegerField(help_text='Weightage (e.g., 5, 10, 15, 20). Total must be 100.')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_parameters', to='iris_app.challenge')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.reviewparameter')),
            ],
            options={
                'db_table': 'IRIS_CHALLENGE_REVIEW_PARAMS',
                'managed': True,
                'unique_together': {('challenge', 'parameter')},
            },
        ),
    ]
