# Generated by Django 5.2.9 on 2026-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0002_rename_business_value_non_monetary_ideadetail_business_monetary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='max_team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='participation_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='registration_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
