# Generated by Django 5.2.9 on 2026-03-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0003_challenge_max_team_size_challenge_participation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='decision',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REWORK', 'Rework')], max_length=20, null=True),
        ),
    ]
