# Generated by Django 5.2.9 on 2025-12-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0003_challenge_challenge_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
