# Generated by Django 5.2.9 on 2026-01-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0005_challenge_round1_eval_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_icon',
            field=models.ImageField(blank=True, null=True, upload_to='challenge_icons/'),
        ),
    ]
