# Generated by Django 5.2.9 on 2026-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0006_alter_challenge_challenge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideadocument',
            name='file_url',
            field=models.FileField(upload_to='idea_documents/'),
        ),
    ]
