# Generated by Django 5.2.9 on 2026-01-05 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0007_alter_ideadocument_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'IRIS_IMPROVEMENT_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrassrootIdea',
            fields=[
                ('idea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_value', models.TextField()),
                ('monetary_value', models.TextField()),
                ('proposed_idea', models.TextField()),
                ('non_monetary_value', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('assumptions', models.TextField()),
                ('key_risks', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED_RM', 'Submitted to RM'), ('REWORK_RM', 'Rework Required by RM'), ('APPROVED_RM', 'Approved by RM'), ('REJECTED_RM', 'Rejected by RM'), ('SUBMITTED_IBU', 'Submitted to IBU'), ('REWORK_IBU', 'Rework Required by IBU'), ('APPROVED_IBU', 'Approved by IBU'), ('REJECTED_IBU', 'Rejected by IBU'), ('PENDING_CUSTOMER', 'Pending Customer Input'), ('COMPLETED', 'Completed')], default='SUBMITTED_RM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidentiality', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('innovation_context', models.CharField(blank=True, max_length=100, null=True)),
                ('ideator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grassroot_ideas', to='iris_app.irisuser')),
                ('improvement_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.improvementcategory')),
            ],
            options={
                'db_table': 'IRIS_GRASSROOT_IDEAS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrassrootEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_role', models.CharField(max_length=20)),
                ('is_desirable', models.BooleanField(default=False)),
                ('is_feasible', models.BooleanField(default=False)),
                ('is_viable', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='iris_app.grassrootidea')),
            ],
            options={
                'db_table': 'IRIS_GRASSROOT_EVALUATIONS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImprovementSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='iris_app.improvementcategory')),
            ],
            options={
                'db_table': 'IRIS_IMPROVEMENT_SUB_CATEGORIES',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='grassrootidea',
            name='improvement_sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_app.improvementsubcategory'),
        ),
    ]
