# Generated by Django 5.2.9 on 2026-01-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_app.irisuser')),
            ],
            options={
                'db_table': 'IRIS_USER_LOGIN_LOGS',
                'ordering': ['-login_at'],
                'managed': True,
            },
        ),
    ]
