# Generated by Django 5.2.9 on 2026-02-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iris_app", "0010_userloginlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrisClusterIbgIbu",
            fields=[
                (
                    "functioncode",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("function_type", models.CharField(max_length=10)),
                ("function_lg_desc", models.CharField(max_length=100)),
                (
                    "function_head",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "function_gdu",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "function_gdu_head",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "function_sdu",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "function_sdu_head",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("function_status", models.CharField(max_length=1)),
                ("function_level", models.CharField(max_length=15)),
                ("function_evp", models.CharField(max_length=11)),
            ],
            options={
                "db_table": "IRIS_CLUSTER_IBG_IBU",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IrisCollage",
            fields=[
                (
                    "collage_id",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=38,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("university_id", models.DecimalField(decimal_places=0, max_digits=38)),
                ("collage_name", models.CharField(max_length=200)),
                (
                    "collage_description",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("created_by", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Collage",
                "verbose_name_plural": "Collages",
                "db_table": "IRIS_COLLAGE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IrisEmployeeMaster",
            fields=[
                (
                    "empcode",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("empname", models.CharField(blank=True, max_length=100, null=True)),
                ("doj", models.DateTimeField(blank=True, null=True)),
                ("emailid", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "prev_exp",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=38, null=True
                    ),
                ),
                (
                    "tm_exp",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=38, null=True
                    ),
                ),
                ("officercode", models.CharField(blank=True, max_length=1, null=True)),
                ("emptitle", models.CharField(blank=True, max_length=50, null=True)),
                ("project_id", models.CharField(blank=True, max_length=20, null=True)),
                ("status_flag", models.CharField(blank=True, max_length=1, null=True)),
                ("jobcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "functioncode",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "base_location",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("supervisor", models.CharField(blank=True, max_length=11, null=True)),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                ("empl_status", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "IRIS_EMPLOYEE_MASTER",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IrisGradeRoleMaster",
            fields=[
                (
                    "role_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(blank=True, max_length=200, null=True)),
                ("sub_band", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "role_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "IRIS_GRADE_ROLE_MASTER",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IrisLocationMaster",
            fields=[
                (
                    "location_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("status_flag", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "IRIS_LOCATION_MASTER",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IrisMailMaster",
            fields=[
                (
                    "status_id",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=38,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mail_subject", models.CharField(max_length=200)),
                ("mail_body", models.CharField(max_length=4000)),
            ],
            options={
                "db_table": "IRIS_MAIL_MASTER",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IrisRoleMs",
            fields=[
                (
                    "rolecode",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=38,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role_sh_desc", models.CharField(max_length=50)),
                ("role_lg_desc", models.CharField(max_length=100)),
                ("grade_desc", models.CharField(blank=True, max_length=5, null=True)),
                ("job_code", models.CharField(blank=True, max_length=10, null=True)),
                ("status_flag", models.CharField(max_length=1)),
                ("job_family", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Role Master",
                "verbose_name_plural": "Role Masters",
                "db_table": "IRIS_ROLE_MS",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="challenge_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_challenges",
                to="iris_app.irisuser",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_challenges",
                to="iris_app.irisuser",
            ),
        ),
    ]
