# Generated by Django 5.2.9 on 2026-02-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iris_app", "0011_irisclusteribgibu_iriscollage_irisemployeemaster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irisuser",
            name="employee_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_users",
                to="iris_app.irisemployeemaster",
            ),
        ),
    ]
