# Generated by Django 5.2.9 on 2026-02-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iris_app", "0012_irisuser_employee_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="ibu_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
