# Generated by Django 5.2.9 on 2026-02-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iris_app", "0014_challenge_round1_eval_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="num_rounds",
            field=models.IntegerField(default=1),
        ),
    ]
