"""
Script to create missing IRIS_IMPROVEMENT_SUB_CATEGORIES table in Oracle.
Run with: venv\Scripts\python.exe create_missing_tables.py
"""
import os
import sys

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'grassroot_iris.settings')

import django
django.setup()

from django.db import connection

def table_exists(cursor, table_name):
    """Check if a table exists in Oracle for the current user."""
    cursor.execute(
        "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = '%s'" % table_name.upper()
    )
    count = cursor.fetchone()[0]
    return count > 0

def main():
    print("Checking Oracle tables...\n")

    with connection.cursor() as cursor:
        # Show all existing tables
        cursor.execute("SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME")
        existing = [row[0] for row in cursor.fetchall()]
        print("Current tables in Oracle:")
        for t in existing:
            print(f"  - {t}")

        # The model uses db_table = 'IRIS_IMPROVEMENT_SUB_CATEGORIES'
        # but Oracle may have truncated this to 30 chars
        target_table = 'IRIS_IMPROVEMENT_SUB_CATEGORIES'
        truncated_name = 'IRIS_IMPROVEMENT_SUB_CATEGDE2E'  # what Oracle created

        print(f"\nChecking for table: {target_table}")
        if target_table in existing:
            print(f"  Table {target_table} EXISTS - no action needed!")
        elif truncated_name in existing:
            print(f"  Found truncated version: {truncated_name}")
            print(f"  This means Oracle truncated the table name.")
            print(f"\n  Solution: Update the model's db_table to match Oracle's actual name.")
            print(f"  Current model setting: db_table = '{target_table}'")
            print(f"  Should be:             db_table = '{truncated_name}'")
        else:
            print(f"  Table does NOT exist. Creating...")
            cursor.execute("""
                CREATE TABLE IRIS_IMPROVEMENT_SUB_CATEGORIES (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    category_id NUMBER NOT NULL,
                    name VARCHAR2(255) NOT NULL,
                    CONSTRAINT fk_isc_cat FOREIGN KEY (category_id)
                        REFERENCES IRIS_IMPROVEMENT_CATEGORIES(id)
                )
            """)
            connection.commit()
            print(f"  Created successfully!")

if __name__ == '__main__':
    main()
